### ISSUE TITLE
Set up GS A/V Testing schedule

### ISSUE THREAD

**Issue by stephwright** [stephwright/Brain#101]
- [x] Set up A/V Testing schedule based off this: https://public.etherpad-mozilla.org/p/sciencelab-2016globalsprint-AV-testing-schedule but here: https://public.etherpad-mozilla.org/p/2017globalsprint-AV-testing-schedule
- [x] Check on Vidyo room set up (JLin? @abbycabs? @auremoser?)
- [x] Send out A/V [testing schedule](https://public.etherpad-mozilla.org/p/2017globalsprint-AV-testing-schedule) and [set-up instructions](https://public.etherpad-mozilla.org/p/2017globalsprint-webconferencing) to host sites
- [x] Add set-up instructions to FAQ blogpost

**Comment by auremoser** [comment]
> Check on Vidyo room set up

I would say JLin if you feel like it needs to be fancy though I think @acabunoc and @arlissc just invited people to their rooms last time, no? I could be totally wrong about that. Thanks for setting this up @stephwright

**Comment by abbycabs** [comment]
Last year @arlissc setup a room specifically for the sprint. The year before that, she booked a physical meeting room for the whole sprint and used that room. I'd loop in JLin if you want to do either!

**Comment by stephwright** [comment]
We already (still) have a room.  You can find it in Vidyo by searching "Global Sprint" or you can use this link: https://v.mozilla.com/flex.html?roomdirect.html&key=8iragD5qYsKNOv11JC6e4Q4UvW8
