### ISSUE TITLE
January 2016 Worklog

### ISSUE THREAD

**Issue by stephwright** [stephwright/Brain#7]
Thanks to @Blahah and @joeyklee setting the example, now using this issue as my worklog.

Old worklog (pre-1/13/2016) can be found here: https://github.com/stephwright/Brain/blob/master/Log/worklog.md

**Comment by stephwright** [comment]
1/13/16 (belatedly added on 1/14)
- MSL stand-up on Gitter
- Helmsley RFP mark-up
- Helmsley RFP call
- Work on "Quick Info" sheets for WOW
- Contact @cbahlai re: WOW workshop on Open Data
- Chat w/ @zee-moz re: WOW deliverables
- WOW Open Data outline

**Comment by stephwright** [comment]
1/14/16
- MSL Community Call
- MSL Fellows call
- belated calendaring for January
- Review @tomhohenstein RDAP poster proposal
- Review event reporter template
- Struggle for over an hour w/ reimbursement issue (argh!!!!)
- Struggle w/ more technology issues requiring repeated reboots (argh!!!!)
- Work on Quick Info Sheet: Why Open Data
- Fix 401K plan registration issue (argh!!!)

**Comment by stephwright** [comment]
1/15/16
- GitHub for Heartbeats training by @cassiemc.
- Update Brain repo w/ labels & milestones
- reach out to Reproducibility contacts re: reproducibility session for @cbahlai course
- continue working on WOW Open Data quick info sheets mozillascience/plan#48

**Comment by stephwright** [comment]
1/19/16
- catch up on email
  - Reproducibility expert recommendation for @cbahlai course
  - plan for putting out call for data reuse case studies
  - connect w/ @joeyklee re: data mgmt learning goals
  - reconnect w/ PNW Data Curators group
  - confirm all swag on its way to Berlin
  - pass along info re: 3D curation in the UK
- Curric Contrib & Participation Group call
- Curriculum Ops call
- continue working on WOW Open Data quick info sheets mozillascience/plan#48
- revisit GitHub for Heartbeats through session 2
- KT 1:1

**Comment by stephwright** [comment]
1/20/16
- begin open data training plan draft issue #10 
  - digging into to program planning in general
- rebuilt open data contacts (KT brainstorm from YYZ locked in old etherpad)
- Chris & MSL call (see etherpad)
- DataONE CEO Working Group call
  - Planning for March & April webinars
  - Review of Lesson 11 hands-on exercise
  - Plan for in-person meeting in Santa Barbara (April or May)
- Finish up draft content for quick-info sheet on Why Open Data (still needs formatting clean-up)
- Flesh out workshop presentation based on feedback from @zee-moz and @kaythaney
  - set-up mtg w/ @zee-moz to clarify schedule and content
- Prep etherpad for Friday's team call

**Comment by stephwright** [comment]
1/21/16
- Conversation w/ @zee-moz re: Open Data workshop
- Hack on Open Data workshop exercise
- Fellows Call
- Conversation w/ @cbahlai re: OSRR course
- Designed [template for Data Reuse Plan and Data Sharing Plan](https://docs.google.com/a/mozilla.com/document/d/1pWqN2yCqD9Az-pVU4mCgM1g_ZCQxNrawF9EgyGqkeyM/edit?usp=sharing)

**Comment by zee-moz** [comment]
Hey, thanks for sending the Data Reuse/Sharing Plan template. Looking good! Will we do a handout in addition to the template, that guides you through the template, or are you talking them through the process during the lecture part of things?

**Comment by stephwright** [comment]
Yes, will be doing the Exercise handout you designed the template for.

**Comment by stephwright** [comment]
1/22/16 OUT SICK
- Team call
- Sleep

**Comment by stephwright** [comment]
1/25/16
- Finished up content in Challenges to Open Data quick info sheet (still needs some design)
- Chat w/ @zee-moz re: materials for @cbahlai course
- Team stand-up call
- Wrote most of script and prepared PPT for @cbahlai course presentation tomorrow
- Finished up Exercise and Data Reuse Template so ready for @cbahlai course.  Will tweak for WOW.
- Added exercise, Data Reuse Template, and quick info sheet to @cbahlai course repo
  - [Exercise](https://github.com/cbahlai/OSRR_course/blob/master/04a_DataReusePlanExercise.md)
  - [Data Reuse Template](https://github.com/cbahlai/OSRR_course/blob/master/04b_Data_Reuse_Plan_Worksheet.md)
  - [Challenges to Open Data Quick Info Sheet](https://github.com/cbahlai/OSRR_course/blob/master/04c_OpenDataChallengesQuickInfoSheet.md)

**Comment by stephwright** [comment]
1/26/16
- Finished up all content for OSRR course
- Curriculum Ops call
- [Presentation](https://docs.google.com/a/mozilla.com/presentation/d/1vOWqL_7MUlEtN4eXQwf36wlmAhYEbhrRNQWp5D9uJws/edit?usp=sharing) to class
- 1:1 w/ KT
- Review some curriculum assessment resources to develop an assessment of today's presentation to OSRR course

**Comment by stephwright** [comment]
1/27/16
- Reviewed Research Parasites twitter feed to catch up on NEMJ hoopla
- Reviewed other news in open data / open sci
- Travel planning: notified financial institutions, scheduled shuttle, set up mobile phone plan
- Team Gitter stand up
- Team call on WOW Prep
- Added OSRR open data materials to [Open Data Training](https://github.com/stephwright/open-data-training) repo
- Went through OSRR materials and revised to make more appropriate for WOW where necessary

**Comment by stephwright** [comment]
1/28/16
- Redesigned Data Reuse Template worksheet for WOW (still in Google Docs: [https://docs.google.com/a/mozilla.com/document/d/1pWqN2yCqD9Az-pVU4mCgM1g_ZCQxNrawF9EgyGqkeyM/edit?usp=sharing])
- Fellows call
- Mozilla Curriculum Team (MCT) call
- Added Data Reuse exercise to new template designed by @flukeout
